#pragma once

#include "conf/config.h"

class LogConfig: public Config
{
    private:
        char log_loc[CONF_MEMBER_LEN];    /** Where to put the log file generated by the logging module */
    public:
        const char* GetLogLocation();
        int SetLogLocation(const char* log_location);
};