// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: icd/v1/icd.proto

#include "icd/v1/icd.pb.h"
#include "icd/v1/icd.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace icd {
namespace v1 {

static const char* TalosOperatorService_method_names[] = {
  "/icd.v1.TalosOperatorService/Handshake",
  "/icd.v1.TalosOperatorService/PolarPanDiscrete",
  "/icd.v1.TalosOperatorService/Home",
  "/icd.v1.TalosOperatorService/PolarPanContinuousStart",
  "/icd.v1.TalosOperatorService/PolarPanContinuousStop",
  "/icd.v1.TalosOperatorService/CartesianMoveDiscrete",
  "/icd.v1.TalosOperatorService/CartesianMoveContinuousStart",
  "/icd.v1.TalosOperatorService/CartesianMoveContinuousStop",
  "/icd.v1.TalosOperatorService/ExecuteHardwareOperation",
  "/icd.v1.TalosOperatorService/GetSpeed",
  "/icd.v1.TalosOperatorService/SetSpeed",
  "/icd.v1.TalosOperatorService/SavePosition",
  "/icd.v1.TalosOperatorService/DeletePosition",
  "/icd.v1.TalosOperatorService/GoToPosition",
  "/icd.v1.TalosOperatorService/SetPolarPosition",
  "/icd.v1.TalosOperatorService/GetPolarPosition",
  "/icd.v1.TalosOperatorService/SetCartesianPosition",
  "/icd.v1.TalosOperatorService/GetCartesianPosition",
};

std::unique_ptr< TalosOperatorService::Stub> TalosOperatorService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TalosOperatorService::Stub> stub(new TalosOperatorService::Stub(channel, options));
  return stub;
}

TalosOperatorService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Handshake_(TalosOperatorService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PolarPanDiscrete_(TalosOperatorService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Home_(TalosOperatorService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PolarPanContinuousStart_(TalosOperatorService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PolarPanContinuousStop_(TalosOperatorService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CartesianMoveDiscrete_(TalosOperatorService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CartesianMoveContinuousStart_(TalosOperatorService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CartesianMoveContinuousStop_(TalosOperatorService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ExecuteHardwareOperation_(TalosOperatorService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSpeed_(TalosOperatorService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetSpeed_(TalosOperatorService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SavePosition_(TalosOperatorService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeletePosition_(TalosOperatorService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GoToPosition_(TalosOperatorService_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetPolarPosition_(TalosOperatorService_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPolarPosition_(TalosOperatorService_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetCartesianPosition_(TalosOperatorService_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetCartesianPosition_(TalosOperatorService_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TalosOperatorService::Stub::Handshake(::grpc::ClientContext* context, const ::icd::v1::HandshakeRequest& request, ::icd::v1::HandshakeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::icd::v1::HandshakeRequest, ::icd::v1::HandshakeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Handshake_, context, request, response);
}

void TalosOperatorService::Stub::async::Handshake(::grpc::ClientContext* context, const ::icd::v1::HandshakeRequest* request, ::icd::v1::HandshakeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::icd::v1::HandshakeRequest, ::icd::v1::HandshakeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Handshake_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::Handshake(::grpc::ClientContext* context, const ::icd::v1::HandshakeRequest* request, ::icd::v1::HandshakeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Handshake_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::icd::v1::HandshakeResponse>* TalosOperatorService::Stub::PrepareAsyncHandshakeRaw(::grpc::ClientContext* context, const ::icd::v1::HandshakeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::icd::v1::HandshakeResponse, ::icd::v1::HandshakeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Handshake_, context, request);
}

::grpc::ClientAsyncResponseReader< ::icd::v1::HandshakeResponse>* TalosOperatorService::Stub::AsyncHandshakeRaw(::grpc::ClientContext* context, const ::icd::v1::HandshakeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHandshakeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TalosOperatorService::Stub::PolarPanDiscrete(::grpc::ClientContext* context, const ::icd::v1::PolarPanDiscreteRequest& request, ::google::protobuf::UInt32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::icd::v1::PolarPanDiscreteRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PolarPanDiscrete_, context, request, response);
}

void TalosOperatorService::Stub::async::PolarPanDiscrete(::grpc::ClientContext* context, const ::icd::v1::PolarPanDiscreteRequest* request, ::google::protobuf::UInt32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::icd::v1::PolarPanDiscreteRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PolarPanDiscrete_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::PolarPanDiscrete(::grpc::ClientContext* context, const ::icd::v1::PolarPanDiscreteRequest* request, ::google::protobuf::UInt32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PolarPanDiscrete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::PrepareAsyncPolarPanDiscreteRaw(::grpc::ClientContext* context, const ::icd::v1::PolarPanDiscreteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::UInt32Value, ::icd::v1::PolarPanDiscreteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PolarPanDiscrete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::AsyncPolarPanDiscreteRaw(::grpc::ClientContext* context, const ::icd::v1::PolarPanDiscreteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPolarPanDiscreteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TalosOperatorService::Stub::Home(::grpc::ClientContext* context, const ::icd::v1::HomeRequest& request, ::google::protobuf::UInt32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::icd::v1::HomeRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Home_, context, request, response);
}

void TalosOperatorService::Stub::async::Home(::grpc::ClientContext* context, const ::icd::v1::HomeRequest* request, ::google::protobuf::UInt32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::icd::v1::HomeRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Home_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::Home(::grpc::ClientContext* context, const ::icd::v1::HomeRequest* request, ::google::protobuf::UInt32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Home_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::PrepareAsyncHomeRaw(::grpc::ClientContext* context, const ::icd::v1::HomeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::UInt32Value, ::icd::v1::HomeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Home_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::AsyncHomeRaw(::grpc::ClientContext* context, const ::icd::v1::HomeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHomeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TalosOperatorService::Stub::PolarPanContinuousStart(::grpc::ClientContext* context, const ::icd::v1::PolarPanContinuousStartRequest& request, ::google::protobuf::UInt32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::icd::v1::PolarPanContinuousStartRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PolarPanContinuousStart_, context, request, response);
}

void TalosOperatorService::Stub::async::PolarPanContinuousStart(::grpc::ClientContext* context, const ::icd::v1::PolarPanContinuousStartRequest* request, ::google::protobuf::UInt32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::icd::v1::PolarPanContinuousStartRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PolarPanContinuousStart_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::PolarPanContinuousStart(::grpc::ClientContext* context, const ::icd::v1::PolarPanContinuousStartRequest* request, ::google::protobuf::UInt32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PolarPanContinuousStart_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::PrepareAsyncPolarPanContinuousStartRaw(::grpc::ClientContext* context, const ::icd::v1::PolarPanContinuousStartRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::UInt32Value, ::icd::v1::PolarPanContinuousStartRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PolarPanContinuousStart_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::AsyncPolarPanContinuousStartRaw(::grpc::ClientContext* context, const ::icd::v1::PolarPanContinuousStartRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPolarPanContinuousStartRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TalosOperatorService::Stub::PolarPanContinuousStop(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::google::protobuf::UInt32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PolarPanContinuousStop_, context, request, response);
}

void TalosOperatorService::Stub::async::PolarPanContinuousStop(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::UInt32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PolarPanContinuousStop_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::PolarPanContinuousStop(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::UInt32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PolarPanContinuousStop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::PrepareAsyncPolarPanContinuousStopRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::UInt32Value, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PolarPanContinuousStop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::AsyncPolarPanContinuousStopRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPolarPanContinuousStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TalosOperatorService::Stub::CartesianMoveDiscrete(::grpc::ClientContext* context, const ::icd::v1::CartesianMoveDiscreteRequest& request, ::google::protobuf::UInt32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::icd::v1::CartesianMoveDiscreteRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CartesianMoveDiscrete_, context, request, response);
}

void TalosOperatorService::Stub::async::CartesianMoveDiscrete(::grpc::ClientContext* context, const ::icd::v1::CartesianMoveDiscreteRequest* request, ::google::protobuf::UInt32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::icd::v1::CartesianMoveDiscreteRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CartesianMoveDiscrete_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::CartesianMoveDiscrete(::grpc::ClientContext* context, const ::icd::v1::CartesianMoveDiscreteRequest* request, ::google::protobuf::UInt32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CartesianMoveDiscrete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::PrepareAsyncCartesianMoveDiscreteRaw(::grpc::ClientContext* context, const ::icd::v1::CartesianMoveDiscreteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::UInt32Value, ::icd::v1::CartesianMoveDiscreteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CartesianMoveDiscrete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::AsyncCartesianMoveDiscreteRaw(::grpc::ClientContext* context, const ::icd::v1::CartesianMoveDiscreteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCartesianMoveDiscreteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TalosOperatorService::Stub::CartesianMoveContinuousStart(::grpc::ClientContext* context, const ::icd::v1::CartesianMoveContinuousStartRequest& request, ::google::protobuf::UInt32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::icd::v1::CartesianMoveContinuousStartRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CartesianMoveContinuousStart_, context, request, response);
}

void TalosOperatorService::Stub::async::CartesianMoveContinuousStart(::grpc::ClientContext* context, const ::icd::v1::CartesianMoveContinuousStartRequest* request, ::google::protobuf::UInt32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::icd::v1::CartesianMoveContinuousStartRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CartesianMoveContinuousStart_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::CartesianMoveContinuousStart(::grpc::ClientContext* context, const ::icd::v1::CartesianMoveContinuousStartRequest* request, ::google::protobuf::UInt32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CartesianMoveContinuousStart_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::PrepareAsyncCartesianMoveContinuousStartRaw(::grpc::ClientContext* context, const ::icd::v1::CartesianMoveContinuousStartRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::UInt32Value, ::icd::v1::CartesianMoveContinuousStartRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CartesianMoveContinuousStart_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::AsyncCartesianMoveContinuousStartRaw(::grpc::ClientContext* context, const ::icd::v1::CartesianMoveContinuousStartRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCartesianMoveContinuousStartRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TalosOperatorService::Stub::CartesianMoveContinuousStop(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::google::protobuf::UInt32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CartesianMoveContinuousStop_, context, request, response);
}

void TalosOperatorService::Stub::async::CartesianMoveContinuousStop(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::UInt32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CartesianMoveContinuousStop_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::CartesianMoveContinuousStop(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::UInt32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CartesianMoveContinuousStop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::PrepareAsyncCartesianMoveContinuousStopRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::UInt32Value, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CartesianMoveContinuousStop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::AsyncCartesianMoveContinuousStopRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCartesianMoveContinuousStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TalosOperatorService::Stub::ExecuteHardwareOperation(::grpc::ClientContext* context, const ::icd::v1::ExecuteHardwareOperationRequest& request, ::icd::v1::ExecuteHardwareOperationResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::icd::v1::ExecuteHardwareOperationRequest, ::icd::v1::ExecuteHardwareOperationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExecuteHardwareOperation_, context, request, response);
}

void TalosOperatorService::Stub::async::ExecuteHardwareOperation(::grpc::ClientContext* context, const ::icd::v1::ExecuteHardwareOperationRequest* request, ::icd::v1::ExecuteHardwareOperationResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::icd::v1::ExecuteHardwareOperationRequest, ::icd::v1::ExecuteHardwareOperationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteHardwareOperation_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::ExecuteHardwareOperation(::grpc::ClientContext* context, const ::icd::v1::ExecuteHardwareOperationRequest* request, ::icd::v1::ExecuteHardwareOperationResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteHardwareOperation_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::icd::v1::ExecuteHardwareOperationResponse>* TalosOperatorService::Stub::PrepareAsyncExecuteHardwareOperationRaw(::grpc::ClientContext* context, const ::icd::v1::ExecuteHardwareOperationRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::icd::v1::ExecuteHardwareOperationResponse, ::icd::v1::ExecuteHardwareOperationRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExecuteHardwareOperation_, context, request);
}

::grpc::ClientAsyncResponseReader< ::icd::v1::ExecuteHardwareOperationResponse>* TalosOperatorService::Stub::AsyncExecuteHardwareOperationRaw(::grpc::ClientContext* context, const ::icd::v1::ExecuteHardwareOperationRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecuteHardwareOperationRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TalosOperatorService::Stub::GetSpeed(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::icd::v1::GetSpeedResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::icd::v1::GetSpeedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSpeed_, context, request, response);
}

void TalosOperatorService::Stub::async::GetSpeed(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::icd::v1::GetSpeedResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::icd::v1::GetSpeedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSpeed_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::GetSpeed(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::icd::v1::GetSpeedResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSpeed_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::icd::v1::GetSpeedResponse>* TalosOperatorService::Stub::PrepareAsyncGetSpeedRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::icd::v1::GetSpeedResponse, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSpeed_, context, request);
}

::grpc::ClientAsyncResponseReader< ::icd::v1::GetSpeedResponse>* TalosOperatorService::Stub::AsyncGetSpeedRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSpeedRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TalosOperatorService::Stub::SetSpeed(::grpc::ClientContext* context, const ::icd::v1::SetSpeedRequest& request, ::google::protobuf::UInt32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::icd::v1::SetSpeedRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetSpeed_, context, request, response);
}

void TalosOperatorService::Stub::async::SetSpeed(::grpc::ClientContext* context, const ::icd::v1::SetSpeedRequest* request, ::google::protobuf::UInt32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::icd::v1::SetSpeedRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetSpeed_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::SetSpeed(::grpc::ClientContext* context, const ::icd::v1::SetSpeedRequest* request, ::google::protobuf::UInt32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetSpeed_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::PrepareAsyncSetSpeedRaw(::grpc::ClientContext* context, const ::icd::v1::SetSpeedRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::UInt32Value, ::icd::v1::SetSpeedRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetSpeed_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::AsyncSetSpeedRaw(::grpc::ClientContext* context, const ::icd::v1::SetSpeedRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetSpeedRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TalosOperatorService::Stub::SavePosition(::grpc::ClientContext* context, const ::icd::v1::SavePositionRequest& request, ::google::protobuf::UInt32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::icd::v1::SavePositionRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SavePosition_, context, request, response);
}

void TalosOperatorService::Stub::async::SavePosition(::grpc::ClientContext* context, const ::icd::v1::SavePositionRequest* request, ::google::protobuf::UInt32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::icd::v1::SavePositionRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SavePosition_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::SavePosition(::grpc::ClientContext* context, const ::icd::v1::SavePositionRequest* request, ::google::protobuf::UInt32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SavePosition_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::PrepareAsyncSavePositionRaw(::grpc::ClientContext* context, const ::icd::v1::SavePositionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::UInt32Value, ::icd::v1::SavePositionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SavePosition_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::AsyncSavePositionRaw(::grpc::ClientContext* context, const ::icd::v1::SavePositionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSavePositionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TalosOperatorService::Stub::DeletePosition(::grpc::ClientContext* context, const ::icd::v1::DeletePositionRequest& request, ::google::protobuf::UInt32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::icd::v1::DeletePositionRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeletePosition_, context, request, response);
}

void TalosOperatorService::Stub::async::DeletePosition(::grpc::ClientContext* context, const ::icd::v1::DeletePositionRequest* request, ::google::protobuf::UInt32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::icd::v1::DeletePositionRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeletePosition_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::DeletePosition(::grpc::ClientContext* context, const ::icd::v1::DeletePositionRequest* request, ::google::protobuf::UInt32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeletePosition_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::PrepareAsyncDeletePositionRaw(::grpc::ClientContext* context, const ::icd::v1::DeletePositionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::UInt32Value, ::icd::v1::DeletePositionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeletePosition_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::AsyncDeletePositionRaw(::grpc::ClientContext* context, const ::icd::v1::DeletePositionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeletePositionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TalosOperatorService::Stub::GoToPosition(::grpc::ClientContext* context, const ::icd::v1::GoToPositionRequest& request, ::google::protobuf::UInt32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::icd::v1::GoToPositionRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GoToPosition_, context, request, response);
}

void TalosOperatorService::Stub::async::GoToPosition(::grpc::ClientContext* context, const ::icd::v1::GoToPositionRequest* request, ::google::protobuf::UInt32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::icd::v1::GoToPositionRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GoToPosition_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::GoToPosition(::grpc::ClientContext* context, const ::icd::v1::GoToPositionRequest* request, ::google::protobuf::UInt32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GoToPosition_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::PrepareAsyncGoToPositionRaw(::grpc::ClientContext* context, const ::icd::v1::GoToPositionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::UInt32Value, ::icd::v1::GoToPositionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GoToPosition_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::AsyncGoToPositionRaw(::grpc::ClientContext* context, const ::icd::v1::GoToPositionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGoToPositionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TalosOperatorService::Stub::SetPolarPosition(::grpc::ClientContext* context, const ::icd::v1::SetPolarPositionRequest& request, ::google::protobuf::UInt32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::icd::v1::SetPolarPositionRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetPolarPosition_, context, request, response);
}

void TalosOperatorService::Stub::async::SetPolarPosition(::grpc::ClientContext* context, const ::icd::v1::SetPolarPositionRequest* request, ::google::protobuf::UInt32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::icd::v1::SetPolarPositionRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetPolarPosition_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::SetPolarPosition(::grpc::ClientContext* context, const ::icd::v1::SetPolarPositionRequest* request, ::google::protobuf::UInt32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetPolarPosition_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::PrepareAsyncSetPolarPositionRaw(::grpc::ClientContext* context, const ::icd::v1::SetPolarPositionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::UInt32Value, ::icd::v1::SetPolarPositionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetPolarPosition_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::AsyncSetPolarPositionRaw(::grpc::ClientContext* context, const ::icd::v1::SetPolarPositionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetPolarPositionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TalosOperatorService::Stub::GetPolarPosition(::grpc::ClientContext* context, const ::icd::v1::GetPolarPositionRequest& request, ::icd::v1::GetPolarPositionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::icd::v1::GetPolarPositionRequest, ::icd::v1::GetPolarPositionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPolarPosition_, context, request, response);
}

void TalosOperatorService::Stub::async::GetPolarPosition(::grpc::ClientContext* context, const ::icd::v1::GetPolarPositionRequest* request, ::icd::v1::GetPolarPositionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::icd::v1::GetPolarPositionRequest, ::icd::v1::GetPolarPositionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPolarPosition_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::GetPolarPosition(::grpc::ClientContext* context, const ::icd::v1::GetPolarPositionRequest* request, ::icd::v1::GetPolarPositionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPolarPosition_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::icd::v1::GetPolarPositionResponse>* TalosOperatorService::Stub::PrepareAsyncGetPolarPositionRaw(::grpc::ClientContext* context, const ::icd::v1::GetPolarPositionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::icd::v1::GetPolarPositionResponse, ::icd::v1::GetPolarPositionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPolarPosition_, context, request);
}

::grpc::ClientAsyncResponseReader< ::icd::v1::GetPolarPositionResponse>* TalosOperatorService::Stub::AsyncGetPolarPositionRaw(::grpc::ClientContext* context, const ::icd::v1::GetPolarPositionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPolarPositionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TalosOperatorService::Stub::SetCartesianPosition(::grpc::ClientContext* context, const ::icd::v1::SetCartesianPositionRequest& request, ::google::protobuf::UInt32Value* response) {
  return ::grpc::internal::BlockingUnaryCall< ::icd::v1::SetCartesianPositionRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetCartesianPosition_, context, request, response);
}

void TalosOperatorService::Stub::async::SetCartesianPosition(::grpc::ClientContext* context, const ::icd::v1::SetCartesianPositionRequest* request, ::google::protobuf::UInt32Value* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::icd::v1::SetCartesianPositionRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetCartesianPosition_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::SetCartesianPosition(::grpc::ClientContext* context, const ::icd::v1::SetCartesianPositionRequest* request, ::google::protobuf::UInt32Value* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetCartesianPosition_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::PrepareAsyncSetCartesianPositionRaw(::grpc::ClientContext* context, const ::icd::v1::SetCartesianPositionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::UInt32Value, ::icd::v1::SetCartesianPositionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetCartesianPosition_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::UInt32Value>* TalosOperatorService::Stub::AsyncSetCartesianPositionRaw(::grpc::ClientContext* context, const ::icd::v1::SetCartesianPositionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetCartesianPositionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status TalosOperatorService::Stub::GetCartesianPosition(::grpc::ClientContext* context, const ::icd::v1::GetCartesianPositionRequest& request, ::icd::v1::GetCartesianPositionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::icd::v1::GetCartesianPositionRequest, ::icd::v1::GetCartesianPositionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetCartesianPosition_, context, request, response);
}

void TalosOperatorService::Stub::async::GetCartesianPosition(::grpc::ClientContext* context, const ::icd::v1::GetCartesianPositionRequest* request, ::icd::v1::GetCartesianPositionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::icd::v1::GetCartesianPositionRequest, ::icd::v1::GetCartesianPositionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCartesianPosition_, context, request, response, std::move(f));
}

void TalosOperatorService::Stub::async::GetCartesianPosition(::grpc::ClientContext* context, const ::icd::v1::GetCartesianPositionRequest* request, ::icd::v1::GetCartesianPositionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetCartesianPosition_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::icd::v1::GetCartesianPositionResponse>* TalosOperatorService::Stub::PrepareAsyncGetCartesianPositionRaw(::grpc::ClientContext* context, const ::icd::v1::GetCartesianPositionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::icd::v1::GetCartesianPositionResponse, ::icd::v1::GetCartesianPositionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetCartesianPosition_, context, request);
}

::grpc::ClientAsyncResponseReader< ::icd::v1::GetCartesianPositionResponse>* TalosOperatorService::Stub::AsyncGetCartesianPositionRaw(::grpc::ClientContext* context, const ::icd::v1::GetCartesianPositionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetCartesianPositionRaw(context, request, cq);
  result->StartCall();
  return result;
}

TalosOperatorService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::icd::v1::HandshakeRequest, ::icd::v1::HandshakeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::icd::v1::HandshakeRequest* req,
             ::icd::v1::HandshakeResponse* resp) {
               return service->Handshake(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::icd::v1::PolarPanDiscreteRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::icd::v1::PolarPanDiscreteRequest* req,
             ::google::protobuf::UInt32Value* resp) {
               return service->PolarPanDiscrete(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::icd::v1::HomeRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::icd::v1::HomeRequest* req,
             ::google::protobuf::UInt32Value* resp) {
               return service->Home(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::icd::v1::PolarPanContinuousStartRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::icd::v1::PolarPanContinuousStartRequest* req,
             ::google::protobuf::UInt32Value* resp) {
               return service->PolarPanContinuousStart(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::google::protobuf::Empty, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::google::protobuf::UInt32Value* resp) {
               return service->PolarPanContinuousStop(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::icd::v1::CartesianMoveDiscreteRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::icd::v1::CartesianMoveDiscreteRequest* req,
             ::google::protobuf::UInt32Value* resp) {
               return service->CartesianMoveDiscrete(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::icd::v1::CartesianMoveContinuousStartRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::icd::v1::CartesianMoveContinuousStartRequest* req,
             ::google::protobuf::UInt32Value* resp) {
               return service->CartesianMoveContinuousStart(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::google::protobuf::Empty, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::google::protobuf::UInt32Value* resp) {
               return service->CartesianMoveContinuousStop(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::icd::v1::ExecuteHardwareOperationRequest, ::icd::v1::ExecuteHardwareOperationResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::icd::v1::ExecuteHardwareOperationRequest* req,
             ::icd::v1::ExecuteHardwareOperationResponse* resp) {
               return service->ExecuteHardwareOperation(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::google::protobuf::Empty, ::icd::v1::GetSpeedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::icd::v1::GetSpeedResponse* resp) {
               return service->GetSpeed(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::icd::v1::SetSpeedRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::icd::v1::SetSpeedRequest* req,
             ::google::protobuf::UInt32Value* resp) {
               return service->SetSpeed(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::icd::v1::SavePositionRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::icd::v1::SavePositionRequest* req,
             ::google::protobuf::UInt32Value* resp) {
               return service->SavePosition(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::icd::v1::DeletePositionRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::icd::v1::DeletePositionRequest* req,
             ::google::protobuf::UInt32Value* resp) {
               return service->DeletePosition(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::icd::v1::GoToPositionRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::icd::v1::GoToPositionRequest* req,
             ::google::protobuf::UInt32Value* resp) {
               return service->GoToPosition(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::icd::v1::SetPolarPositionRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::icd::v1::SetPolarPositionRequest* req,
             ::google::protobuf::UInt32Value* resp) {
               return service->SetPolarPosition(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::icd::v1::GetPolarPositionRequest, ::icd::v1::GetPolarPositionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::icd::v1::GetPolarPositionRequest* req,
             ::icd::v1::GetPolarPositionResponse* resp) {
               return service->GetPolarPosition(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::icd::v1::SetCartesianPositionRequest, ::google::protobuf::UInt32Value, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::icd::v1::SetCartesianPositionRequest* req,
             ::google::protobuf::UInt32Value* resp) {
               return service->SetCartesianPosition(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TalosOperatorService_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TalosOperatorService::Service, ::icd::v1::GetCartesianPositionRequest, ::icd::v1::GetCartesianPositionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TalosOperatorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::icd::v1::GetCartesianPositionRequest* req,
             ::icd::v1::GetCartesianPositionResponse* resp) {
               return service->GetCartesianPosition(ctx, req, resp);
             }, this)));
}

TalosOperatorService::Service::~Service() {
}

::grpc::Status TalosOperatorService::Service::Handshake(::grpc::ServerContext* context, const ::icd::v1::HandshakeRequest* request, ::icd::v1::HandshakeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TalosOperatorService::Service::PolarPanDiscrete(::grpc::ServerContext* context, const ::icd::v1::PolarPanDiscreteRequest* request, ::google::protobuf::UInt32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TalosOperatorService::Service::Home(::grpc::ServerContext* context, const ::icd::v1::HomeRequest* request, ::google::protobuf::UInt32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TalosOperatorService::Service::PolarPanContinuousStart(::grpc::ServerContext* context, const ::icd::v1::PolarPanContinuousStartRequest* request, ::google::protobuf::UInt32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TalosOperatorService::Service::PolarPanContinuousStop(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::UInt32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TalosOperatorService::Service::CartesianMoveDiscrete(::grpc::ServerContext* context, const ::icd::v1::CartesianMoveDiscreteRequest* request, ::google::protobuf::UInt32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TalosOperatorService::Service::CartesianMoveContinuousStart(::grpc::ServerContext* context, const ::icd::v1::CartesianMoveContinuousStartRequest* request, ::google::protobuf::UInt32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TalosOperatorService::Service::CartesianMoveContinuousStop(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::google::protobuf::UInt32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TalosOperatorService::Service::ExecuteHardwareOperation(::grpc::ServerContext* context, const ::icd::v1::ExecuteHardwareOperationRequest* request, ::icd::v1::ExecuteHardwareOperationResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TalosOperatorService::Service::GetSpeed(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::icd::v1::GetSpeedResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TalosOperatorService::Service::SetSpeed(::grpc::ServerContext* context, const ::icd::v1::SetSpeedRequest* request, ::google::protobuf::UInt32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TalosOperatorService::Service::SavePosition(::grpc::ServerContext* context, const ::icd::v1::SavePositionRequest* request, ::google::protobuf::UInt32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TalosOperatorService::Service::DeletePosition(::grpc::ServerContext* context, const ::icd::v1::DeletePositionRequest* request, ::google::protobuf::UInt32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TalosOperatorService::Service::GoToPosition(::grpc::ServerContext* context, const ::icd::v1::GoToPositionRequest* request, ::google::protobuf::UInt32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TalosOperatorService::Service::SetPolarPosition(::grpc::ServerContext* context, const ::icd::v1::SetPolarPositionRequest* request, ::google::protobuf::UInt32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TalosOperatorService::Service::GetPolarPosition(::grpc::ServerContext* context, const ::icd::v1::GetPolarPositionRequest* request, ::icd::v1::GetPolarPositionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TalosOperatorService::Service::SetCartesianPosition(::grpc::ServerContext* context, const ::icd::v1::SetCartesianPositionRequest* request, ::google::protobuf::UInt32Value* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status TalosOperatorService::Service::GetCartesianPosition(::grpc::ServerContext* context, const ::icd::v1::GetCartesianPositionRequest* request, ::icd::v1::GetCartesianPositionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace icd
}  // namespace v1

